### ISSUE TITLE
工具栏图片icon不显示

### ISSUE THREAD

**Issue by JackFrancisLiu** [yanmao-cc/am-editor#53]
![微信图片_20211112092500](https://user-images.githubusercontent.com/25114528/141416422-8ec71bd8-f40f-4efc-8209-595cbe2df586.png)
如图所示，demo里的工具栏图标不显示。还有就是工具栏插件在项目里使用后图标还是不显示，作者辛苦看下，点赞

**Comment by yanmao-cc** [comment]
是在内网吗？无法加载到 //at.alicdn.com/t/font_1456030_mvh913k905.woff2?t=1629619375484 这个？

**Comment by JackFrancisLiu** [comment]
> 是在内网吗？无法加载到 //at.alicdn.com/t/font_1456030_mvh913k905.woff2?t=1629619375484 这个？

对，应该是因为内网的原因，需要把这个链接下载到本地是吧

> 是在内网吗？无法加载到 //at.alicdn.com/t/font_1456030_mvh913k905.woff2?t=1629619375484 这个？

你那边方便的话把fonticon的包地址直接发给我，我去阿里妈妈下载一套到本地

**Comment by yanmao-cc** [comment]
现在看起来下载下来除非你把系统 host 文件改了at.alicdn.com 指向到本地服务，不然也无法使用。晚点我把这个文件放在本地再去编译吧。就这三个文件

src: url('//at.alicdn.com/t/font_1456030_mvh913k905.woff2?t=1629619375484') format('woff2'),
         url('//at.alicdn.com/t/font_1456030_mvh913k905.woff?t=1629619375484') format('woff'),
         url('//at.alicdn.com/t/font_1456030_mvh913k905.ttf?t=1629619375484') format('truetype');

**Comment by JackFrancisLiu** [comment]
> 现在看起来下载下来除非你把系统 host 文件改了at.alicdn.com 指向到本地服务，不然也无法使用。晚点我把这个文件放在本地再去编译吧。就这三个文件
> 
> src: url('//at.alicdn.com/t/font_1456030_mvh913k905.woff2?t=1629619375484') format('woff2'), url('//at.alicdn.com/t/font_1456030_mvh913k905.woff?t=1629619375484') format('woff'), url('//at.alicdn.com/t/font_1456030_mvh913k905.ttf?t=1629619375484') format('truetype');

行，那等你本地版发版了，我看还是四天前的版本，有空麻烦发个本地版，感谢

**Comment by yanmao-cc** [comment]
你可以在本地项目中通过css把编辑器中的样式覆盖即可 

这里 src 的url改为你本地项目的地址
```less
@font-face {
    font-family: "data-icon"; /* Project id 1456030 */
    src: url('//at.alicdn.com/t/font_1456030_mvh913k905.woff2?t=1629619375484') format('woff2'),
         url('//at.alicdn.com/t/font_1456030_mvh913k905.woff?t=1629619375484') format('woff'),
         url('//at.alicdn.com/t/font_1456030_mvh913k905.ttf?t=1629619375484') format('truetype');
  }  
```
这是字体文件
[download.zip](https://github.com/yanmao-cc/am-editor/files/7543252/download.zip)
